title: Stryphe's struggle bus
author: stryphe
email: strifethejunglistking@gmail.com  
description: > # this means to ignore newlines until "baseurl:"
An old fart trying to learn new things
# social links
twitter_username: your-twitter-handle # who tweets other than Donald trump?
github_username:  your-github-handle # stryphe
show_excerpts: true # False
theme: minima
